In [1]:
import numpy as np

array = np.zeros((3, 4))
print(array)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
import numpy as np

random_array = np.random.randint(1, 11, size=20)
reshaped_array = random_array.reshape(4, 5)

print(reshaped_array)


[[3 8 4 1 6]
 [3 5 1 1 8]
 [8 7 6 6 2]
 [4 1 3 5 5]]


In [5]:
import numpy as np


identity_matrix = np.eye(5)
diagonal_elements = np.diagonal(identity_matrix)

print("Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [7]:
import numpy as np


even_array = np.arange(10, 10 + 4 * 5 * 2, 2).reshape(4, 5)
third_column = even_array[:, 2]

even_array[3] = [1, 2, 3, 4, 5]
print("Original 4x5 Array of Even Numbers:")
print(even_array)

print("\nThird Column:")
print(third_column)


Original 4x5 Array of Even Numbers:
[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [ 1  2  3  4  5]]

Third Column:
[14 24 34  3]


In [11]:
import numpy as np

names = np.array(["Roxana", "Statira", "Roxana", "Statira", "Roxana"])
score = np.array([126, 115, 130, 141, 132])

scores_below_130 = score[score < 130]
scores_statira = score[names == "Statira"]
score[names == "Roxana"] += 10

print("Scores below 130:", scores_below_130)
print("Scores by Statira:", scores_statira)
print("Updated scores:", score)


Scores below 130: [126 115]
Scores by Statira: [115 141]
Updated scores: [136 115 140 141 142]


In [13]:
import pandas as pd


df = pd.read_csv('data.csv')  
print(df.head())


FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'