In [1]:
import numpy as np
a=[]
n=int(input("Enter a size of list:"))
for i in range(n):
    val=int(input("Enter a value"))
    a.append(val)
myarr=np.array(a)
myarr

Enter a size of list: 5
Enter a value 1
Enter a value 2
Enter a value 3
Enter a value 4
Enter a value 5


array([1, 2, 3, 4, 5])

In [10]:
import numpy as np
myarr=np.array([[3,4,5,6]],np.int32 )
myarr

array([[3, 4, 5, 6]], dtype=int32)

In [12]:
myarr[0,1]

4

In [4]:
 myarr.shape

(1, 4)

 # ARRAY creation using PYTHON object
 

In [17]:
Listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
Listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
Listarray.shape

(3, 3)

In [21]:
Listarray.size

9

In [25]:
Listarray.dtype

dtype('int64')

In [29]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [31]:
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
zeros.size

10

In [35]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
lspace=np.linspace(1,4,8 )
lspace

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

In [41]:
lspace=np.linspace(1,8,8 )
lspace

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [43]:
emp=np.empty((4,6))
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [45]:
emp_like=np.empty_like(lspace)
emp_like

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [47]:
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [51]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [55]:
arr=arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [57]:
arr=arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [61]:
arr.shape

(99,)

# NUMPY AXIS

In [66]:
x = ([[1,2,3],[4,5,6],[7,8,9]])
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
ar.sum(axis=0)

array([12, 15, 18])

In [70]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [72]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [74]:
ar.flat

In [76]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [78]:
ar.ndim

2

In [80]:
ar.size

9

In [82]:
ar.nbytes

72

In [86]:
one = np.array([1,3,4,345,2])
one.argmax()

3

In [88]:
one.argmin()

0

In [90]:
one.argsort()

array([0, 4, 1, 2, 3])

In [92]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
ar.argmin()

0

In [96]:
ar.argmax()

8

In [98]:
ar.argmax(axis=1)

array([2, 2, 2])

In [100]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [102]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [106]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
ar2=np.array([[2,4,6],[1,3,5],[3,5,7]])
ar2

array([[2, 4, 6],
       [1, 3, 5],
       [3, 5, 7]])

In [110]:
ar+ar2

array([[ 3,  6,  9],
       [ 5,  8, 11],
       [10, 13, 16]])

In [112]:
[32,34]+[21,23]

[32, 34, 21, 23]

In [114]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
ar2

array([[2, 4, 6],
       [1, 3, 5],
       [3, 5, 7]])

In [118]:
ar*ar2

array([[ 2,  8, 18],
       [ 4, 15, 30],
       [21, 40, 63]])

In [120]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [124]:
ar.sum()

45

In [126]:
ar.max()

9

In [128]:
ar.min()

1

In [130]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [132]:
np.where(ar>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [134]:
np.count_nonzero(ar)

9

In [136]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [138]:
ar[1,2]=0
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [140]:
import sys
ch_ar = [0,4,55,2]
np_ar=np.array(ch_ar)
sys.getsizeof(1)*len(ch_ar)

112

In [146]:
np_ar.itemsize * np_ar.size

32

In [148]:
np_ar.tolist()

[0, 4, 55, 2]